// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Aquarius.Data.Tests.Migrations
{
    public sealed partial class Init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init));
        
        string IMigrationMetadata.Id
        {
            get { return "201308201455526_Init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
